### ISSUE TITLE
course.classes error

### ISSUE THREAD

**Issue by Barloew** [robbertkl/Magister#1]
I get the following error when I run this:

  /usr/src/app/index.js:57
	course.classes(function(error, courseClasses) {
	       ^
TypeError: Cannot read property 'classes' of undefined
    at fetchClasses (/usr/src/app/index.js:57:9)
    at /usr/src/app/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/usr/src/app/node_modules/async/dist/async.js:1055:9)
    at eachOf (/usr/src/app/node_modules/async/dist/async.js:1103:5)
    at _parallel (/usr/src/app/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/usr/src/app/node_modules/async/dist/async.js:3948:5)
    at /usr/src/app/index.js:20:11
    at /usr/src/app/node_modules/magister.js/lib/node/magister-node.js:2747:18
    at /usr/src/app/node_modules/magister.js/lib/node/magister-node.js:2722:20
    at Request._callback (/usr/src/app/node_modules/magister.js/lib/node/magister-

**Comment by robbertkl** [comment]
Hi Barlow, can you tell me what versions you're using? Node version, package versions (`npm list`), specifically of the magister.js package.

It's working fine here, so perhaps the library has been updated and I need to make a compatibility fix (or just tie down the specific version)

**Comment by Barloew** [comment]
Hi Robbert,

Thank you for commenting to my issue so promptly. I totally missed it. Please accept my apologies for not responding sooner!

I have two installations. One on a RPI3 and the other as a Docker Container on a Synology DS710+, pulled from the Docker Hub. I just downloaded and ran the latest version. Both produce completely identical errors. Versions in use on the Raspberry PI as follows.

magister@1.0.0 /usr/local/lib/node_modules/magister-grades
├─┬ async@2.6.0
│ └── lodash@4.17.4
├─┬ magister.js@1.24.2
│ ├── lodash@3.10.1
│ └─┬ request@2.81.0
│   ├── aws-sign2@0.6.0
│   ├── aws4@1.5.0
│   ├── caseless@0.12.0
│   ├─┬ combined-stream@1.0.5
│   │ └── delayed-stream@1.0.0
│   ├── extend@3.0.1
│   ├── forever-agent@0.6.1
│   ├─┬ form-data@2.1.4
│   │ ├── asynckit@0.4.0
│   │ ├── combined-stream@1.0.5 deduped
│   │ └── mime-types@2.1.12 deduped
│   ├─┬ har-validator@4.2.1
│   │ ├─┬ ajv@4.11.8
│   │ │ ├── co@4.6.0
│   │ │ └─┬ json-stable-stringify@1.0.1
│   │ │   └── jsonify@0.0.0
│   │ └── har-schema@1.0.5
│   ├─┬ hawk@3.1.3
│   │ ├─┬ boom@2.10.1
│   │ │ └── hoek@2.16.3 deduped
│   │ ├─┬ cryptiles@2.0.5
│   │ │ └── boom@2.10.1 deduped
│   │ ├── hoek@2.16.3
│   │ └─┬ sntp@1.0.9
│   │   └── hoek@2.16.3 deduped
│   ├─┬ http-signature@1.1.1
│   │ ├── assert-plus@0.2.0
│   │ ├─┬ jsprim@1.3.1
│   │ │ ├── extsprintf@1.0.2
│   │ │ ├── json-schema@0.2.3
│   │ │ └─┬ verror@1.3.6
│   │ │   └── extsprintf@1.0.2 deduped
│   │ └─┬ sshpk@1.10.1
│   │   ├── asn1@0.2.3
│   │   ├── assert-plus@1.0.0
│   │   ├─┬ bcrypt-pbkdf@1.0.0
│   │   │ └── tweetnacl@0.14.3 deduped
│   │   ├─┬ dashdash@1.14.0
│   │   │ └── assert-plus@1.0.0
│   │   ├─┬ ecc-jsbn@0.1.1
│   │   │ └── jsbn@0.1.0 deduped
│   │   ├─┬ getpass@0.1.7
│   │   │ └── assert-plus@1.0.0
│   │   ├─┬ jodid25519@1.0.2
│   │   │ └── jsbn@0.1.0 deduped
│   │   ├── jsbn@0.1.0
│   │   └── tweetnacl@0.14.3
│   ├── is-typedarray@1.0.0
│   ├── isstream@0.1.2
│   ├── json-stringify-safe@5.0.1
│   ├─┬ mime-types@2.1.12
│   │ └── mime-db@1.24.0
│   ├── oauth-sign@0.8.2
│   ├── performance-now@0.2.0
│   ├── qs@6.2.1
│   ├── safe-buffer@5.1.1
│   ├── stringstream@0.0.5
│   ├── tough-cookie@2.3.1
│   ├─┬ tunnel-agent@0.6.0
│   │ └── safe-buffer@5.1.1 deduped
│   └── uuid@3.1.0
└─┬ nodemailer@2.7.2
  ├─┬ libmime@3.0.0
  │ ├── iconv-lite@0.4.15
  │ ├── libbase64@0.1.0
  │ └── libqp@1.1.0
  ├─┬ mailcomposer@4.0.1
  │ ├─┬ buildmail@4.0.1
  │ │ ├── addressparser@1.0.1
  │ │ ├── libbase64@0.1.0 deduped
  │ │ ├── libmime@3.0.0 deduped
  │ │ ├── libqp@1.1.0 deduped
  │ │ ├── nodemailer-fetch@1.6.0 deduped
  │ │ ├── nodemailer-shared@1.1.0 deduped
  │ │ └── punycode@1.4.1
  │ └── libmime@3.0.0 deduped
  ├─┬ nodemailer-direct-transport@3.3.2
  │ ├── nodemailer-shared@1.1.0 deduped
  │ └─┬ smtp-connection@2.12.0
  │   ├─┬ httpntlm@1.6.1
  │   │ ├── httpreq@0.4.24
  │   │ └── underscore@1.7.0
  │   └── nodemailer-shared@1.1.0 deduped
  ├─┬ nodemailer-shared@1.1.0
  │ └── nodemailer-fetch@1.6.0
  ├─┬ nodemailer-smtp-pool@2.8.2
  │ ├── nodemailer-shared@1.1.0 deduped
  │ ├── nodemailer-wellknown@0.1.10
  │ └── smtp-connection@2.12.0 deduped
  ├─┬ nodemailer-smtp-transport@2.7.2
  │ ├── nodemailer-shared@1.1.0 deduped
  │ ├── nodemailer-wellknown@0.1.10 deduped
  │ └── smtp-connection@2.12.0 deduped
  └─┬ socks@1.1.9
    ├── ip@1.1.5
    └── smart-buffer@1.1.15

Appreciate your advise in this.

**Comment by robbertkl** [comment]
It's been a long time, and I've made some changes/updates since this issue. Closing it now, but feel free to reopen if you're still experiencing issues.
